server:
  port: 8084

spring:
  application:
    name: notification-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queues:
    order-created: order.created
    order-assigned: order.assigned
