server:
  port: 8083

spring:
  application:
    name: tracking-service
  datasource:
    url: jdbc:postgresql://tracking-db:5432/trackingdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queues:
    order-created: order.created
    order-assigned: order.assigned
